Shorten `library_name` to 200 chars as the 3.8 compat tests can fail due to library name length:
FAILED tests/integration/arcticdb/test_arctic.py::test_dedup[real_s3-EncodingVersion.V1] - arcticdb_ext.exceptions.UserInputException: The library name length exceeds the max supported length. library name length: 255, Max Supported Length: 254
FAILED tests/integration/arcticdb/test_arctic.py::test_dedup[real_s3-EncodingVersion.V2] - arcticdb_ext.exceptions.UserInputException: The library name length exceeds the max supported length. library name length: 255, Max Supported Length: 254
= 2 failed, 1200 passed, 2977 skipped, 12 xfailed, 2 xpassed, 366 warnings in 6386.76s (1:46:26) =