Use Pandas unpickling to handle Pandas 1 vs Pandas 2 API differences better (#2151)
For pickled dataframes, such as Pandas objects saved in our `metadata`.

Before this, reading a dataframe like the one in the test in this PR
would fail with a Pandas 2 venv with:

```
In [8]: lib.read("tst")
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[8], line 1
----> 1 lib.read("tst")

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/version_store/library.py:1496, in Library.read(self, symbol, as_of, date_range, row_range, columns, query_builder, lazy)
   1484     return LazyDataFrame(
   1485         self,
   1486         ReadRequest(
   (...)
   1493         ),
   1494     )
   1495 else:
-> 1496     return self._nvs.read(
   1497         symbol=symbol,
   1498         as_of=as_of,
   1499         date_range=date_range,
   1500         row_range=row_range,
   1501         columns=columns,
   1502         query_builder=query_builder,
   1503         implement_read_index=True,
   1504         iterate_snapshots_if_tombstoned=False,
   1505     )

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/version_store/_store.py:1775, in NativeVersionStore.read(self, symbol, as_of, date_range, row_range, columns, query_builder, **kwargs)
   1766 version_query, read_options, read_query = self._get_queries(
   1767     as_of=as_of,
   1768     date_range=date_range,
   (...)
   1772     **kwargs,
   1773 )
   1774 read_result = self._read_dataframe(symbol, version_query, read_query, read_options)
-> 1775 return self._post_process_dataframe(read_result, read_query, implement_read_index)

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/version_store/_store.py:1875, in NativeVersionStore._post_process_dataframe(self, read_result, read_query, implement_read_index, head, tail)
   1872         data.append(c[start_idx:end_idx])
   1873     read_result.frame_data = FrameData(data, read_result.frame_data.names, read_result.frame_data.index_columns)
-> 1875 vitem = self._adapt_read_res(read_result)
   1877 # Handle custom normalized data
   1878 if len(read_result.keys) > 0:

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/version_store/_store.py:2086, in NativeVersionStore._adapt_read_res(self, read_result)
   2084 def _adapt_read_res(self, read_result: ReadResult) -> VersionedItem:
   2085     frame_data = FrameData.from_cpp(read_result.frame_data)
-> 2086     meta = denormalize_user_metadata(read_result.udm, self._normalizer)
   2087     data = self._normalizer.denormalize(frame_data, read_result.norm)
   2088     if read_result.norm.HasField("custom"):

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/version_store/_normalization.py:1321, in denormalize_user_metadata(udm, ext_obj)
   1319 storage_type = udm.WhichOneof("storage_type")
   1320 if storage_type == "inline_payload":
-> 1321     return _msgpack_metadata._msgpack_unpackb(udm.inline_payload)
   1322 elif storage_type is None:
   1323     return None

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/version_store/_normalization.py:1043, in MsgPackNormalizer._msgpack_unpackb(self, buff, raw)
   1042 def _msgpack_unpackb(self, buff, raw=False):
-> 1043     return unpackb(buff, raw=raw, ext_hook=self._ext_hook)

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/_msgpack_compat.py:53, in unpackb(packed, **kwargs)
     51 if msgpack.version >= (0, 6, 0):
     52     kwargs.setdefault("strict_map_key", False)
---> 53 return msgpack.unpackb(packed, **kwargs)

File msgpack/_unpacker.pyx:194, in msgpack._cmsgpack.unpackb()

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/version_store/_normalization.py:1032, in MsgPackNormalizer._ext_hook(self, code, data)
   1030 if code == MsgPackSerialization.PY_PICKLE_3:
   1031     data = unpackb(data, raw=False)
-> 1032     return Pickler.read(data, pickled_in_python2=False)
   1034 return ExtType(code, data)

File ~/venvs/310-3/lib/python3.10/site-packages/arcticdb/version_store/_normalization.py:1057, in Pickler.read(data, pickled_in_python2)
   1054         return pickle.loads(data, encoding="bytes")
   1056 try:
-> 1057     return pickle.loads(data)
   1058 except UnicodeDecodeError as exc:
   1059     log.debug("Failed decoding with ascii, using latin-1.")

ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'
```