Adapt signature of `read_dataframe_from_file`
Given:

```
2025-03-26T15:53:44.0857462Z D:\a\ArcticDB\ArcticDB\cpp\arcticdb\version\python_bindings.cpp(235): error C2440: 'return': cannot convert from 'pybind11::tuple (__cdecl *)(arcticdb::VariantId,const std::string,std::shared_ptr<arcticdb::pipelines::ReadQuery> &,const arcticdb::ReadOptions &)' to 'pybind11::tuple (__cdecl *)(arcticdb::VariantId,const std::string (__cdecl *)(void),std::shared_ptr<arcticdb::pipelines::ReadQuery> &,const arcticdb::ReadOptions &)'
2025-03-26T15:53:44.1099966Z D:\a\ArcticDB\ArcticDB\cpp\arcticdb\version\python_bindings.cpp(235): note: This conversion requires a reinterpret_cast, a C-style cast or function-style cast
2025-03-26T15:53:44.1430769Z D:\a\ArcticDB\ArcticDB\cpp\arcticdb\version\python_bindings.cpp(235): error C2440: 'return': cannot convert from 'pybind11::tuple (__vectorcall *)(arcticdb::VariantId,const std::string,std::shared_ptr<arcticdb::pipelines::ReadQuery> &,const arcticdb::ReadOptions &)' to 'pybind11::tuple (__vectorcall *)(arcticdb::VariantId,const std::string (__cdecl *)(void),std::shared_ptr<arcticdb::pipelines::ReadQuery> &,const arcticdb::ReadOptions &)'
2025-03-26T15:53:59.0922987Z D:\a\ArcticDB\ArcticDB\cpp\arcticdb\version\python_bindings.cpp(235): note: This conversion requires a reinterpret_cast, a C-style cast or function-style cast
```

Signed-off-by: Julien Jerphanion <git@jjerphan.xyz>