Increase tolerance to arithmetic mismatches with Pandas with floats (#2333)
#### Reference Issues/PRs

https://github.com/man-group/ArcticDB/actions/runs/14487537861/job/40636907727?pr=2331

#### What does this implement or fix?
To resolve this type of flakiness:

``` python
FAILED tests/hypothesis/arcticdb/test_resample.py::test_resample - AssertionError: Series are different

Series values are different (100.0 %)
[index]: [1969-12-31T23:59:01.000000000]
[left]:  [-1706666.6666666667]
[right]: [-1706325.3333333333]
At positional index 0, first diff: -1706666.6666666667 != -1706325.3333333333
Falsifying example: test_resample(
    df=
                                       col_float              col_int  col_uint
        1970-01-01 00:00:00.000000000        0.0  9223372036849590785         0
        1970-01-01 00:00:00.000000001        0.0                  512         0
        1970-01-01 00:00:00.000000002        0.0 -9223372036854710785         0
    ,
    rule='1min',
    origin='start',
    offset='1s',
)

You can reproduce this example by temporarily adding @reproduce_failure('6.72.4', b'AXicY2RgYGQAYxCCUEwMyAAkzVD/Hwg2PGIEq2ACqgASjBDR/0yMMFUwAAB9FAui') as a decorator on your test case
```

#### Any other comments?
A similar fix was done here:
https://github.com/man-group/ArcticDB/commit/fe9de294580526e921102fbdedda736f20596fc7

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
- [ ] Have you updated the relevant docstrings, documentation and
copyright notice?
- [ ] Is this contribution tested against [all ArcticDB's
features](../docs/mkdocs/docs/technical/contributing.md)?
- [ ] Do all exceptions introduced raise appropriate [error
messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
- [ ] Is the PR labelled as enhancement or bug so it appears in
autogenerated release notes?
</details>

<!--
Thanks for contributing a Pull Request to ArcticDB! Please ensure you
have taken a look at:
- ArcticDB's Code of Conduct:
https://github.com/man-group/ArcticDB/blob/master/CODE_OF_CONDUCT.md
- ArcticDB's Contribution Licensing:
https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md#contribution-licensing
-->