Retry pip install to reduce failures and update list of versions we test (#2442)
#### Reference Issues/PRs
<!--Example: Fixes #1234. See also #3456.-->

#### What does this implement or fix?

Log:
https://github.com/man-group/ArcticDB/actions/runs/16096913268/job/45420945182

```
× Download failed because not enough bytes were received (9.4 MB/17.5 MB)
╰─> URL: https://files.pythonhosted.org/packages/8e/[59](https://github.com/man-group/ArcticDB/actions/runs/16096913268/job/45420945182#step:7:60)/2b0ea84b8[61](https://github.com/man-group/ArcticDB/actions/runs/16096913268/job/45420945182#step:7:62)a2a8069c3df6f44fe97bd3af5c3e61fea921d458829718d65/arcticdb-5.6.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

note: This is an issue with network connectivity, not pip.
hint: Consider using --resume-retries to enable download resumption.
Error: Process completed with exit code 1.
```

5.6 Test log:
https://github.com/man-group/ArcticDB/actions/runs/16109291472/job/45449848101
5.7 (new):
https://github.com/man-group/ArcticDB/actions/runs/16109448740
5.8 (new):
https://github.com/man-group/ArcticDB/actions/runs/16109369289

#### Any other comments?

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
- [ ] Have you updated the relevant docstrings, documentation and
copyright notice?
- [ ] Is this contribution tested against [all ArcticDB's
features](../docs/mkdocs/docs/technical/contributing.md)?
- [ ] Do all exceptions introduced raise appropriate [error
messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
- [ ] Is the PR labelled as enhancement or bug so it appears in
autogenerated release notes?
</details>

<!--
Thanks for contributing a Pull Request to ArcticDB! Please ensure you
have taken a look at:
- ArcticDB's Code of Conduct:
https://github.com/man-group/ArcticDB/blob/master/CODE_OF_CONDUCT.md
- ArcticDB's Contribution Licensing:
https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md#contribution-licensing
-->