Test for test_admin_tools.py::test_get_sizes_for_symbol flakyness (#2398)
#### Reference Issues/PRs
<!--Example: Fixes #1234. See also #3456.-->

#### What does this implement or fix?

Chasing instable test with azurite fixture
test_admin_tools.py::test_get_sizes_for_symbol flakyness, see bellow
test failure log. There is an excaption:

```
 arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Error: AzureError#0 :  Connection was closed by the server while trying to read a response for object test_get_sizes_for_symbol_azur/6553377_21159_139944093017152_2025-04-17T11_06_14_507386_ed65cc05-5641-4cc8-8176-2dfdf9f854671744887974511308032/ver/*sTt*sym_1
```

at the call ```non_existent_sizes =
arctic_library.admin_tools().get_sizes_for_symbol("non-existent")```

Initial tests for flakiness:
https://github.com/man-group/ArcticDB/actions/runs/15561527422

https://github.com/man-group/ArcticDB/actions/runs/15554106058/job/43790643810

Show things like:

```
OSError: [Errno 28] No space left on device
=========================== short test summary info ============================
FAILED python/tests/integration/arcticdb/test_admin_tools.py::test_get_sizes_for_symbol[nfs_backed_s3-0-231-1000] - arcticdb_ext.exceptions.StorageException: E_S3_RETRYABLE Retry-able error: Unexpected error: S3Error#1 :  for object 'test_get_sizes_for_symbol_nfs_/43452_140704547392000_2025-06-10T10_54_21__eaff5022-ae2f-4c16-85fb-19e18c5272201749552861542121984/tdata/338/352/*sTt*rec__0*0*1749552870711318000*8976788147767758352*0*100000'
FAILED python/tests/integration/arcticdb/test_admin_tools.py::test_get_sizes_for_symbol[nfs_backed_s3-1-314-1000] - arcticdb_ext.exceptions.StorageException: E_S3_RETRYABLE Retry-able error: Unexpected error: S3Error#1 :  for object 'test_get_sizes_for_symbol_nfs_/43455_140704547392000_2025-06-10T10_54_20__2c1c21a6-234a-4746-a239-a14bedaf513f1749552860053722112/tdata/338/914/*sTt*rec__0*0*1749552872269569000*1934416323169649914*100000*200000'
```

and  

```
System.IO.IOException: No space left on device : '/home/runner/runners/2.325.0/_diag/Worker_20250610-140333-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
```

Those findings suggest that Moto simulator we run demands disk space for
each execution. That means that potentially each test can fail not only
azurite. One solution is not using disk for simulator (how) and another
is using much less if no option to run in memory. But perhaps most
important question is why this happens? Doesn't moto clean things after
each test?

-------------------
First Attempt - instead of df with 250k rows lets use 2.5k and rerun
test
Log: https://github.com/man-group/ArcticDB/actions/runs/15576877019
The problem does not reproduce. But may be it is due to lower dataframe
size?

-------------------
Second Attempt - back to 250k dataframe this time azurite tests wipe out
libs at end. Run only azurite tests using command:
```
pytest  -v -n 6 --count=1500 -x python/tests/integration/arcticdb/test_admin_tools_2.py
```
see this special change:
https://github.com/man-group/ArcticDB/pull/2398/commits/359cc057ea31dcad3a88f648159255ad0560e702
Log: https://github.com/man-group/ArcticDB/actions/runs/15604010078
Analysis: we see lots of internal server errors 500 when writing to
azzurite:
We do not see out of space disk errors
Could this be a problem with limited number of file descriptors?
```
=========================== short test summary info ============================
FAILED python/tests/integration/arcticdb/test_admin_tools_2.py::test_get_sizes_by_symbol[azurite-EncodingVersion.V1-790-1500] - arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Server Error: AzureError#500 : Internal Server Error 500 Internal Server Error

Request ID:  for object test_get_sizes_by_symbol_azuri/337_140538255984448_2025-06-12T07_25_33__d69b9317-163c-4534-9bbe-35a56e153b0c1749713133913234944/tdata/*sTt*rec__0*0*1749713143039627481*2167427990096510081*200000*250000
FAILED python/tests/integration/arcticdb/test_admin_tools_2.py::test_get_sizes_by_symbol[azurite-EncodingVersion.V1-40-1500] - arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Server Error: AzureError#500 : Internal Server Error 500 Internal Server Error

Request ID:  for object test_get_sizes_by_symbol_azuri/329_140680803247936_2025-06-12T07_25_37__375f4e0e-fb0b-4d66-9747-57abe9ca152d1749713137536886784/tdata/*sTt*sym_1*2*1749713144202813284*10129017941298964712*200000*250000
FAILED python/tests/integration/arcticdb/test_admin_tools_2.py::test_get_sizes[azurite-EncodingVersion.V2-800-1500] - arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Server Error: AzureError#500 : Internal Server Error 500 Internal Server Error

Request ID:  for object test_get_sizes_azurite_Encodin/333_140326579201856_2025-06-12T07_28_07__c074b2b6-3e77-470e-8c5d-70b35d002e6b1749713287391098112/tdata/*sTt*sym_1*2*1749713291095980285*4111217884356261613*0*100000
FAILED python/tests/integration/arcticdb/test_admin_tools_2.py::test_get_sizes[azurite-EncodingVersion.V2-48-1500] - arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Server Error: AzureError#500 : Internal Server Error 500 Internal Server Error

Request ID:  for object test_get_sizes_azurite_Encodin/341_139690105362240_2025-06-12T07_28_04__22700935-7a1a-4181-8fd0-54a3d2ea51e31749713284382380288/tdata/*sTt*rec__1*0*1749713290432246861*4869874623346023949*0*100000
FAILED python/tests/integration/arcticdb/test_admin_tools_2.py::test_get_sizes[azurite-EncodingVersion.V1-815-1500] - arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Server Error: AzureError#500 : Internal Server Error 500 Internal Server Error

Request ID:  for object test_get_sizes_azurite_Encodin/322_140101243885376_2025-06-12T07_28_05__4af51649-737e-4a06-a1be-f56226629d681749713285035569664/tdata/*sTt*rec__0*0*1749713290932919156*17035343310716093125*0*100000
FAILED python/tests/integration/arcticdb/test_admin_tools_2.py::test_get_sizes[azurite-EncodingVersion.V1-65-1500] - arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Server Error: AzureError#500 : Internal Server Error 500 Internal Server Error
```
-------------------
Third attempt - use same code for tests just add logging for azurite and
also collection of logs so we can see what happens:
Log:
https://github.com/man-group/ArcticDB/actions/runs/15608938969/job/43965421003
Azurite log:
https://github.com/man-group/ArcticDB/actions/runs/15608938969/artifacts/3313739644

Errors there: 
```
2025-06-12T11:25:57.859Z 75d3c03a-0cdc-4524-b942-46cc75f42866 debug: FSExtentStore:streamPipe() Writable stream triggers error event, error:{"errno":-28,"code":"ENOSPC","syscall":"write"}, after 262144 bytes piped. Reject streamPipe().
2025-06-12T11:25:57.860Z 75d3c03a-0cdc-4524-b942-46cc75f42866 debug: OperationQueue.operate() Job 98b8b662-eff7-43b3-8f05-ec36cee9d9ec error, reject.
2025-06-12T11:25:57.860Z 75d3c03a-0cdc-4524-b942-46cc75f42866 error: ErrorMiddleware: Received an error, fill error information to HTTP response
2025-06-12T11:25:57.860Z 75d3c03a-0cdc-4524-b942-46cc75f42866 error: ErrorMiddleware: ErrorName=Error ErrorMessage=ENOSPC: no space left on device, write ErrorStack="Error: ENOSPC: no space left on device, write"
2025-06-12T11:25:57.860Z 75d3c03a-0cdc-4524-b942-46cc75f42866 error: ErrorMiddleware: Set HTTP code: 500

```
Question: in the new version of tests the tests do delete librararies,
however this does not seem to free space claimed?

-------------------

Final Solution - as the original problem was not reproduced due to many
factors final solution implemented has a test operation
retry_get_sizes() that will will do 3 retries on the original operation
if experiences same azurite error only. That wil either:

1. solve the issue if it was a problem with that opperation temprorary
error
OR
2. move the problem with azurite further down the lines. Azurite does
not seem very reliable under load and some errors may emerge later

-------------------

Test Failure Log:
```
=================================== FAILURES ===================================

22772

_____________________ test_get_sizes_for_symbol[azurite-0] _____________________

22773

[gw1] linux -- Python 3.13.3 /home/runner/micromamba/envs/arcticdb/bin/python

22774

 

22775

arctic_client = Arctic(config=azure(endpoint=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=...;BlobEndpoint=http://localhost:11180/devstoreaccount1, container=container3338159e))

22776

lib_name = 'test_get_sizes_for_symbol_azur.6553377_21159_139944093017152_2025-04-17T11_06_14_507386_ed65cc05-5641-4cc8-8176-2dfdf9f85467'

22777

 

22778

    def test_get_sizes_for_symbol(arctic_client, lib_name):

22779

        lib_opts = EnterpriseLibraryOptions(replication=True)

22780

        arctic_library = arctic_client.create_library(lib_name, enterprise_library_options=lib_opts)

22781

        arctic_library.write_pickle("sym_1", 1)

22782

        arctic_library.write_pickle("sym_1", 2)

22783

        df = sample_dataframe(size=250_000)

22784

        arctic_library.write("sym_1", df)

22785

        arctic_library.delete("sym_1", versions=[0])

22786

   

22787

        arctic_library.write_pickle("delete_me", 1)

22788

        arctic_library.delete("delete_me")

22789

   

22790

        non_existent_sizes = arctic_library.admin_tools().get_sizes_for_symbol("non-existent")

22791

   

22792

        expected_key_types = {KeyType.VERSION_REF, KeyType.VERSION, KeyType.TABLE_INDEX, KeyType.TABLE_DATA, KeyType.APPEND_DATA, KeyType.MULTI_KEY}

22793

        assert non_existent_sizes.keys() == expected_key_types

22794

        for size in non_existent_sizes.values():

22795

            assert size == Size(0, 0)

22796

   

22797

        deleted_sizes = arctic_library.admin_tools().get_sizes_for_symbol("delete_me")

22798

        assert deleted_sizes.keys() == expected_key_types

22799

        assert deleted_sizes[KeyType.VERSION_REF].count == 1

22800

        assert deleted_sizes[KeyType.VERSION].count == 2

22801

        for t in (KeyType.TABLE_INDEX, KeyType.TABLE_DATA, KeyType.APPEND_DATA):

22802

            assert deleted_sizes[t] == Size(0, 0)

22803

   

22804

>       sizes = arctic_library.admin_tools().get_sizes_for_symbol("sym_1")

22805

 

22806

tests/integration/arcticdb/test_admin_tools.py:159:

22807

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

22808

 

22809

self = <arcticdb.version_store.admin_tools.AdminTools object at 0x7f46b79e6fd0>

22810

symbol = 'sym_1'

22811

 

22812

    def get_sizes_for_symbol(self, symbol: str) -> Dict[KeyType, Size]:

22813

        """

22814

        A breakdown of compressed sizes (in bytes) used by the given symbol, grouped by key type.

22815

   

22816

        The following key types (and only these) are always included in the output:

22817

   

22818

        ```

22819

        VERSION_REF

22820

        VERSION

22821

        TABLE_INDEX

22822

        TABLE_DATA

22823

        APPEND_DATA

22824

        ```

22825

   

22826

        Does not raise if the symbol does not exist.

22827

        """

22828

>       sizes = self._nvs.version_store.scan_object_sizes_for_stream(symbol)

22829

E       arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Error: AzureError#0 :  Connection was closed by the server while trying to read a response for object test_get_sizes_for_symbol_azur/6553377_21159_139944093017152_2025-04-17T11_06_14_507386_ed65cc05-5641-4cc8-8176-2dfdf9f854671744887974511308032/ver/*sTt*sym_1
```

#### Any other comments?

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
- [ ] Have you updated the relevant docstrings, documentation and
copyright notice?
- [ ] Is this contribution tested against [all ArcticDB's
features](../docs/mkdocs/docs/technical/contributing.md)?
- [ ] Do all exceptions introduced raise appropriate [error
messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
- [ ] Is the PR labelled as enhancement or bug so it appears in
autogenerated release notes?
</details>

<!--
Thanks for contributing a Pull Request to ArcticDB! Please ensure you
have taken a look at:
- ArcticDB's Code of Conduct:
https://github.com/man-group/ArcticDB/blob/master/CODE_OF_CONDUCT.md
- ArcticDB's Contribution Licensing:
https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md#contribution-licensing
-->

---------

Co-authored-by: Georgi Rusev <Georgi Rusev>