Fix for file descriptors for v1 StorageFixtures [Partially fixes the problem] version 2 (#2431)
#### Reference Issues/PRs
<!--Example: Fixes #1234. See also #3456.-->

#### What does this implement or fix?

The main problem is stated with previous
[PR#2411](https://github.com/man-group/ArcticDB/pull/2411)

This PR explores better fix with much less code having the same outcome
- reducing the file descriptors but perhaps not eliminating constant
growth

NOTE : The gains in terms of file descriptors are same as the other PR -
40-50% less filedescptors use. Still file descriptors grow and there
could be other sources of leakage hidden

NOTE 2: The time for executions is at par compared to master branch.
Unit tests also keep same speed, as in this version LMDB storage is not
cleaned (cleaning LMDB storage on Windows has surprising side effect -
produces no space left on disk errors for unit tests)

Overall this version does address the problem, without claiming it is
solved. File desciptors are yet suspicios, but at least reduced in half.
This does not translate to loss of performance. The code is also small
and very clean and easy to understand and maintain

Also, some typehints added where were missing

Proof works with AWS
https://github.com/man-group/ArcticDB/actions/runs/16000056800
GCP: https://github.com/man-group/ArcticDB/actions/runs/16018002964
Conda: https://github.com/man-group/ArcticDB/actions/runs/16027025454
LMDB: https://github.com/man-group/ArcticDB/actions/runs/16027093639

There are MacOS related errors:

When this is present, the tests does not complete: 
```
Error: nfig.py::test_set_log_level[ERROR] 
Error:  90%] PASSED tests/integration/arcticdb/test_config.py::test_set_log_level[ERROR] 
```

There is also memory related flakyness (3 times) with stress test: As
MacOs is new platform the limit on MacOS will be increased
```
FAILED tests/stress/arcticdb/version_store/test_mem_leaks.py::test_mem_leak_read_all_native_store - AssertionError: Memory of the process grew more than defined threshold:  658.22MB/[690192384]  (specified:  580.47MB/[608662528]  )
assert 608662528 >= 690192384
```

An error:, caused by python crashing
https://github.com/man-group/ArcticDB/actions/runs/16027093639/job/45218574977
```
[gw1] [ 98%] PASSED tests/stress/arcticdb/version_store/test_stress_finalize_staged_data.py::test_finalize_monotonic_unique_chunks[lmdb-0] 
test_stress_finalize_staged_data.py::test_finalize_monotonic_unique_chunks[lmdb-1] Fatal Python error: Aborted

Thread 0x000000016edf3000 (most recent call first):
..................
FAILED tests/stress/arcticdb/version_store/test_stress_finalize_staged_data.py::test_finalize_monotonic_unique_chunks[lmdb-1]
```

Another test failed due to crash: 
```
[gw2] [ 97%] FAILED tests/nonreg/arcticdb/version_store/test_nonreg_specific.py::test_update_int_nan[lmdb_version_store_dynamic_schema_v1] 
replacing crashed worker gw2
```

IMPORTANT, crashes are not related to this particular PR, they exist on
Master and MacOS:
https://github.com/man-group/ArcticDB/actions/runs/16042098834/job/45265831896
(this time on another tests)

DECISION:
- test_config.py::test_set_log_level - escaping now
- test_mem_leaks.py::test_mem_leak_read_all_native_store
- For crashes - no action

LMDB additional run:
https://github.com/man-group/ArcticDB/actions/runs/16044422289

Addressing crashes - skipping tests for now and some other fixes for
MacOS ARM specific:

LMDB - additional tests
https://github.com/man-group/ArcticDB/actions/runs/16048431365
LMDB https://github.com/man-group/ArcticDB/actions/runs/16052756922 
LMDB https://github.com/man-group/ArcticDB/actions/runs/16067316663
LMDB https://github.com/man-group/ArcticDB/actions/runs/16068135282

ALL SUCCESS from first time:
LMDB: https://github.com/man-group/ArcticDB/actions/runs/16068135282
LMDB: https://github.com/man-group/ArcticDB/actions/runs/16067996042
AWS: https://github.com/man-group/ArcticDB/actions/runs/16070660124
GCP: https://github.com/man-group/ArcticDB/actions/runs/16073761598

#### Any other comments?

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
- [ ] Have you updated the relevant docstrings, documentation and
copyright notice?
- [ ] Is this contribution tested against [all ArcticDB's
features](../docs/mkdocs/docs/technical/contributing.md)?
- [ ] Do all exceptions introduced raise appropriate [error
messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
- [ ] Is the PR labelled as enhancement or bug so it appears in
autogenerated release notes?
</details>

<!--
Thanks for contributing a Pull Request to ArcticDB! Please ensure you
have taken a look at:
- ArcticDB's Code of Conduct:
https://github.com/man-group/ArcticDB/blob/master/CODE_OF_CONDUCT.md
- ArcticDB's Contribution Licensing:
https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md#contribution-licensing
-->

---------

Co-authored-by: Georgi Rusev <Georgi Rusev>