Upgrade curl to >=8.18 (#2853)
#### Reference Issues/PRs
<!--Example: Fixes #1234. See also #3456.-->

#### What does this implement or fix?
Uprgrades `libcurl >= 8.18` both for vcpkg and conda.

Also removes the `libsodium` dependency which is no longer required
(because we're using a [vcpkg
override](https://github.com/man-group/ArcticDB/blob/534b2f27a1497e9da565ec1b14818360239ae481/cpp/third_party/vcpkg_overlays/folly/0001-fix-deps.patch#L158-L162)
to deal with folly's use of libsodium).


#### Any other comments?
`libcurl==8.17` specifically have issues with Azure and GCP seen
[here](https://github.com/man-group/ArcticDB/actions/runs/20994418585/job/60348350103?pr=2855):
```
FAILED tests/integration/arcticdb/test_arctic.py::test_s3_verification[s3_storage-ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.NOT_SHOW] - arcticdb_ext.exceptions.StorageException: E_S3_RETRYABLE Retry-able error: Network error: S3Error:99, HttpResponseCode:-1, : curlCode: 60, SSL peer certificate or SSH remote key was not OK for object '_arctic_cfg/cref/*sUt*test_s3_verification_s3_storag.353_140621644920640_2026-01-14T13_08_29__010ce6a9-001f-4b48-b4e9-0ae2f10cd8a6' This could be due to a connectivity issue or exhausted file descriptors. Having more than one open Arctic instance will use multiple file descriptors, you should reuse Arctic instances. If you need many file descriptors, consider increasing `ulimit -n`.
FAILED tests/integration/arcticdb/test_arctic.py::test_s3_verification[s3_storage-ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.DISABLE] - arcticdb_ext.exceptions.StorageException: E_S3_RETRYABLE Retry-able error: Network error: S3Error:99, HttpResponseCode:-1, : curlCode: 60, SSL peer certificate or SSH remote key was not OK for object '_arctic_cfg/cref/*sUt*test_s3_verification_s3_storag.353_140621644920640_2026-01-14T13_09_21__16b2e8f5-dc91-4dcc-a61f-1f51b511ef24' This could be due to a connectivity issue or exhausted file descriptors. Having more than one open Arctic instance will use multiple file descriptors, you should reuse Arctic instances. If you need many file descriptors, consider increasing `ulimit -n`.
FAILED tests/integration/arcticdb/test_arctic.py::test_s3_verification[gcp_storage-ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.NOT_SHOW] - arcticdb_ext.exceptions.StorageException: E_S3_RETRYABLE Retry-able error: Network error: S3Error:99, HttpResponseCode:-1, : curlCode: 60, SSL peer certificate or SSH remote key was not OK for object '_arctic_cfg/cref/*sUt*test_s3_verification_gcp_stora.353_140621644920640_2026-01-14T13_10_30__e5380d58-9897-4275-a830-0b3abf6f6105' This could be due to a connectivity issue or exhausted file descriptors. Having more than one open Arctic instance will use multiple file descriptors, you should reuse Arctic instances. If you need many file descriptors, consider increasing `ulimit -n`.
FAILED tests/integration/arcticdb/test_arctic.py::test_s3_verification[gcp_storage-ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.DISABLE] - arcticdb_ext.exceptions.StorageException: E_S3_RETRYABLE Retry-able error: Network error: S3Error:99, HttpResponseCode:-1, : curlCode: 60, SSL peer certificate or SSH remote key was not OK for object '_arctic_cfg/cref/*sUt*test_s3_verification_gcp_stora.353_140621644920640_2026-01-14T13_11_22__cf83e471-6acf-4442-aab6-732db9ddcfd5' This could be due to a connectivity issue or exhausted file descriptors. Having more than one open Arctic instance will use multiple file descriptors, you should reuse Arctic instances. If you need many file descriptors, consider increasing `ulimit -n`.
FAILED tests/integration/arcticdb/test_azure_transport.py::test_azurite_ssl_verification[ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.NOT_SHOW] - arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Error: AzureError#0 :  Fail to get a new connection for: https://localhost:11359. SSL peer certificate or SSH remote key was not OK. Underlying error: unable to get local issuer certificate for object _arctic_cfg/cref/*sUt*test_azurite_ssl_verification_.359_139923536713536_2026-01-14T13_13_53__49d6bf92-87e4-453e-8e3d-249cec1517f4
FAILED tests/integration/arcticdb/test_azure_transport.py::test_azurite_ssl_verification[ParameterDisplayStatus.ENABLE-ParameterDisplayStatus.DISABLE] - arcticdb_ext.exceptions.StorageException: E_UNEXPECTED_AZURE_ERROR Unexpected Error: AzureError#0 :  Fail to get a new connection for: https://localhost:11359. SSL peer certificate or SSH remote key was not OK. Underlying error: unable to get local issuer certificate for object _arctic_cfg/cref/*sUt*test_azurite_ssl_verification_.359_139923536713536_2026-01-14T13_14_06__a42b55bd-6082-4d51-bc2f-751387a626a0
```

The issues are not present with 8.18 as seen by the green CI on this PR.

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
- [ ] Have you updated the relevant docstrings, documentation and
copyright notice?
- [ ] Is this contribution tested against [all ArcticDB's
features](../docs/mkdocs/docs/technical/contributing.md)?
- [ ] Do all exceptions introduced raise appropriate [error
messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
- [ ] Is the PR labelled as enhancement or bug so it appears in
autogenerated release notes?
</details>

<!--
Thanks for contributing a Pull Request to ArcticDB! Please ensure you
have taken a look at:
- ArcticDB's Code of Conduct:
https://github.com/man-group/ArcticDB/blob/master/CODE_OF_CONDUCT.md
- ArcticDB's Contribution Licensing:
https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md#contribution-licensing
-->